# Generated by Django 4.2.10 on 2024-04-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
